#!/usr/bin/with-contenv bashio
# ==============================================================================
# Generates /etc/caddy/Caddyfile from add-on options.
# ==============================================================================
set -e

CADDYFILE="/etc/caddy/Caddyfile"
mkdir -p "$(dirname "${CADDYFILE}")"

{
    echo "# Auto-generated by ha-caddy add-on. Do not edit by hand."
    echo "{"

    if bashio::config.has_value 'email'; then
        echo "    email $(bashio::config 'email')"
    fi

    if bashio::config.has_value 'log_level'; then
        echo "    log {"
        echo "        level $(bashio::config 'log_level' | tr '[:lower:]' '[:upper:]')"
        echo "    }"
    fi

    echo "}"
    echo ""
} > "${CADDYFILE}"

if ! bashio::config.has_value 'proxies'; then
    bashio::log.warning "No 'proxies' configured — Caddy will only answer on default ports."
fi

for index in $(bashio::config 'proxies|keys'); do
    domain=$(bashio::config "proxies[${index}].domain")
    upstream=$(bashio::config "proxies[${index}].upstream")

    if ! bashio::var.has_value "${domain}" || ! bashio::var.has_value "${upstream}"; then
        bashio::log.warning "Skipping proxy entry ${index}: missing domain or upstream."
        continue
    fi

    bashio::log.info "Configuring proxy: ${domain} → ${upstream}"

    {
        echo "${domain} {"
        if bashio::config.exists "proxies[${index}].tls" \
            && bashio::config.false "proxies[${index}].tls"; then
            echo "    tls internal"
        fi
        echo "    reverse_proxy ${upstream}"
        echo "}"
        echo ""
    } >> "${CADDYFILE}"
done

if bashio::config.has_value 'extra_caddyfile'; then
    {
        echo "# --- extra_caddyfile ---"
        bashio::config 'extra_caddyfile'
        echo ""
    } >> "${CADDYFILE}"
fi

bashio::log.info "Generated Caddyfile:"
cat "${CADDYFILE}"

bashio::log.info "Validating generated Caddyfile..."
if ! caddy validate --config "${CADDYFILE}" --adapter caddyfile; then
    bashio::log.fatal "Caddyfile validation failed."
    bashio::exit.nok
fi

bashio::log.info "Caddyfile is valid."
