#!/usr/bin/with-contenv bashio
# ==============================================================================
# Generates /etc/caddy/Caddyfile from add-on options.
# ==============================================================================
set -e

CADDYFILE="/etc/caddy/Caddyfile"
LOG_DIR="/data/logs"
INGRESS_PORT=8099
mkdir -p "$(dirname "${CADDYFILE}")" "${LOG_DIR}"

ACCESS_LOG=$(bashio::config 'access_log')
ROLL_SIZE=$(bashio::config 'access_log_roll_size_mb')
ROLL_KEEP=$(bashio::config 'access_log_roll_keep')
: "${ROLL_SIZE:=10}"
: "${ROLL_KEEP:=5}"

# ----- Global block -----
{
    echo "# Auto-generated by ha-caddy add-on. Do not edit by hand."
    echo "{"

    if bashio::config.has_value 'email'; then
        echo "    email $(bashio::config 'email')"
    fi

    if bashio::config.has_value 'log_level'; then
        echo "    log {"
        echo "        level $(bashio::config 'log_level' | tr '[:lower:]' '[:upper:]')"
        echo "    }"
    fi

    # Order required by handle directives for path routing.
    echo "    order rate_limit before basicauth"
    echo "}"
    echo ""
} > "${CADDYFILE}"

# ----- Ingress block (status page) -----
{
    echo ":${INGRESS_PORT} {"
    echo "    root * /opt/ha-caddy/web"
    echo "    file_server"
    echo "    encode gzip"
    echo "}"
    echo ""
} >> "${CADDYFILE}"

if ! bashio::config.has_value 'proxies'; then
    bashio::log.warning "No 'proxies' configured."
fi

# ----- Per-proxy blocks -----
for index in $(bashio::config 'proxies|keys'); do
    domain=$(bashio::config "proxies[${index}].domain")
    default_upstream=$(bashio::config "proxies[${index}].upstream")

    if ! bashio::var.has_value "${domain}"; then
        bashio::log.warning "Skipping proxy ${index}: missing domain."
        continue
    fi

    # Collect routes (path-based routing).
    routes_count=0
    if bashio::config.exists "proxies[${index}].routes"; then
        routes_count=$(bashio::config "proxies[${index}].routes|length" || echo 0)
    fi

    if [[ "${routes_count}" -eq 0 ]] && ! bashio::var.has_value "${default_upstream}"; then
        bashio::log.warning "Skipping ${domain}: no upstream and no routes."
        continue
    fi

    bashio::log.info "Configuring ${domain} (routes=${routes_count})"

    log_file_name="${domain//\*/_}"
    log_file_name="${log_file_name//\//_}"

    {
        echo "${domain} {"

        if bashio::config.exists "proxies[${index}].tls" \
            && bashio::config.false "proxies[${index}].tls"; then
            echo "    tls internal"
        fi

        if [[ "${ACCESS_LOG}" != "false" ]]; then
            echo "    log {"
            echo "        output file ${LOG_DIR}/${log_file_name}.log {"
            echo "            roll_size ${ROLL_SIZE}MiB"
            echo "            roll_keep ${ROLL_KEEP}"
            echo "        }"
            echo "        format json"
            echo "    }"
        fi

        if bashio::config.true "proxies[${index}].security_headers"; then
            echo "    header {"
            echo "        Strict-Transport-Security \"max-age=31536000; includeSubDomains\""
            echo "        X-Content-Type-Options \"nosniff\""
            echo "        Referrer-Policy \"strict-origin-when-cross-origin\""
            echo "        -Server"
            echo "    }"
        fi

        # Rate limiting (caddy-ratelimit plugin).
        rl_events=$(bashio::config "proxies[${index}].rate_limit_events" || true)
        rl_window=$(bashio::config "proxies[${index}].rate_limit_window" || true)
        if bashio::var.has_value "${rl_events}" && bashio::var.has_value "${rl_window}"; then
            echo "    rate_limit {"
            echo "        zone proxy_${index} {"
            echo "            key {remote_host}"
            echo "            events ${rl_events}"
            echo "            window ${rl_window}"
            echo "        }"
            echo "    }"
        fi

        # Path-based routes via handle blocks for ordering.
        if [[ "${routes_count}" -gt 0 ]]; then
            for r in $(seq 0 $((routes_count - 1))); do
                rpath=$(bashio::config "proxies[${index}].routes[${r}].path")
                rup=$(bashio::config "proxies[${index}].routes[${r}].upstream")
                echo "    handle ${rpath} {"
                echo "        reverse_proxy ${rup}"
                echo "    }"
            done
            if bashio::var.has_value "${default_upstream}"; then
                echo "    handle {"
                echo "        reverse_proxy ${default_upstream}"
                echo "    }"
            fi
        else
            echo "    reverse_proxy ${default_upstream}"
        fi

        echo "}"
        echo ""
    } >> "${CADDYFILE}"
done

if bashio::config.has_value 'extra_caddyfile'; then
    {
        echo "# --- extra_caddyfile ---"
        bashio::config 'extra_caddyfile'
        echo ""
    } >> "${CADDYFILE}"
fi

bashio::log.info "Generated Caddyfile:"
cat "${CADDYFILE}"

bashio::log.info "Validating generated Caddyfile..."
if ! caddy validate --config "${CADDYFILE}" --adapter caddyfile; then
    bashio::log.fatal "Caddyfile validation failed."
    bashio::exit.nok
fi

bashio::log.info "Caddyfile is valid."
